version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SqlServer
    environment:
      SA_PASSWORD: "!123DojoCsharp"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G